/* AUTHENTICATION */
// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
// Check sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
// Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// Edit region
export const AUTH_EDIT_REGION = "AUTH_EDIT_REGION";
export const AUTH_EDIT_REGION_SUCCESS = "AUTH_EDIT_REGION_SUCCESS";
export const AUTH_EDIT_REGION_FAILURE = "AUTH_EDIT_REGION_FAILURE";
// Order (account)
export const AUTH_ORDER = "AUTH_ORDER";
export const AUTH_ORDER_SUCCESS = "AUTH_ORDER_SUCCESS";
export const AUTH_ORDER_FAILURE = "AUTH_ORDER_FAILURE";
/* Store */
// register store
export const STORE_REGISTER = "STORE_REGISTER";
export const STORE_REGISTER_SUCCESS = "STORE_REGISTER_SUCCESS";
export const STORE_REGISTER_FAILURE = "STORE_REGISTER_FAILURE";
// get stores
export const STORE_LIST = "STORE_LIST";
export const STORE_LIST_SUCCESS = "STORE_LIST_SUCCESS";
export const STORE_LIST_FAILURE = "STORE_LIST_FAILURE";
// get one stores
export const STORE_ONE = "STORE_ONE";
export const STORE_ONE_SUCCESS = "STORE_ONE_SUCCESS";
export const STORE_ONE_FAILURE = "STORE_ONE_FAILURE";
// edit store
export const STORE_EDIT = "STORE_EDIT";
export const STORE_EDIT_SUCCESS = "STORE_EDIT_SUCCESS";
export const STORE_EDIT_FAILURE = "STORE_EDIT_FAILURE";
// save store
export const STORE_SAVE = "STORE_SAVE";
export const STORE_SAVE_SUCCESS = "STORE_SAVE_SUCCESS";
export const STORE_SAVE_FAILURE = "STORE_SAVE_FAILURE";
// retrieve my save store
export const STORE_SAVE_RETRIEVE = "STORE_SAVE_RETRIEVE";
export const STORE_SAVE_RETRIEVE_SUCCESS = "STORE_SAVE_RETRIEVE_SUCCESS";
export const STORE_SAVE_RETRIEVE_FAILURE = "STORE_SAVE_RETRIEVE_FAILURE";
// Order (store)
export const STORE_ORDER = "STORE_ORDER";
export const STORE_ORDER_SUCCESS = "STORE_ORDER_SUCCESS";
export const STORE_ORDER_FAILURE = "STORE_ORDER_FAILURE";
// Reivew
export const STORE_REVIEW = "STORE_REVIEW";
export const STORE_REVIEW_SUCCESS = "STORE_REVIEW_SUCCESS";
export const STORE_REVIEW_FAILURE = "STORE_REVIEW_FAILURE";
// EDIT Reivew
export const STORE_EDIT_REVIEW = "STORE_EDIT_REVIEW";
export const STORE_EDIT_REVIEW_SUCCESS = "STORE_EDIT_REVIEW_SUCCESS";
export const STORE_EDIT_REVIEW_FAILURE = "STORE_EDIT_REVIEW_FAILURE";
// Search
export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
